package com.example.railway.domain;

public enum NotificationType {
    ORDER_CREATED,
    PAYMENT_SUCCEEDED,
    TICKET_ISSUED,
    ORDER_CLOSED,
    ORDER_REFUNDED,
    REFUND_SUCCEEDED,
    REFUND_FAILED,
    TICKET_CHANGE_CREATED,
    TICKET_CHANGE_PENDING_PAYMENT,
    TICKET_CHANGE_SUCCEEDED,
    TICKET_CHANGE_FAILED,
    RISK_ALERT
}
